---
# tasks file for edgeos-zone

- name: Backup config
  edgeos_config:
    backup: yes
    backup_options:
      dir_path: ~/_erl_backup
      #~ filename: config.boot-cmd-{{ erlcfg.system.hostname }}.{{ erlcfg.system.domain_name }}

- name: Generate configuration file. | Template version Zero (0).
  template:
    src: ercfgz.j2
    dest: ~/_ans_tmp/config.boot-{{ erlcfg.system.hostname }}.{{ erlcfg.system.domain_name }}
  when: >
    TEMPLATE_VERSION is not defined

- name: Template | Version 1
  #~ include: tmpl_v1.yml
  template:
    src: config.boot-v1.j2
    dest: ~/_ans_tmp/config.boot-{{ erlcfg.system.hostname }}.{{ erlcfg.system.domain_name }}
  when: > 
    TEMPLATE_VERSION is defined and
    TEMPLATE_VERSION == 1

- name: Push configuration to router.
  edgeos_config:
    src: ~/_ans_tmp/config.boot-{{ erlcfg.system.hostname }}.{{ erlcfg.system.domain_name }}
