---
# tasks file for edgeos-zone

- name: Backup config
  edgeos_config:
    backup: yes
    backup_options:
      filename: config.boot.command.{{ erlcfg.system.hostname }}.{{ erlcfg.system.domain_name }}
      dir_path: /home/user/erl/backup

- include: tmpl_v1.yml
  when: > 
    TEMPLATE_VERSION == 1

- name: Push configuration to router.
  edgeos_config:
    src: ~/_ans_tmp/config.boot-{{ erlcfg.system.hostname }}.{{ erlcfg.system.domain_name }}
