---
# tasks file for edgeos-zone

- name: Backup config
  edgeos_config:
    backup: yes
    backup_options:
      dir_path: ~/_erl_other/backup
      #~ filename: config.boot.command.{{ erlcfg.system.hostname }}.{{ erlcfg.system.domain_name }}

- name: Template | Version 1
  include: tmpl_v1.yml
  when: > 
    TEMPLATE_VERSION is defined and
    TEMPLATE_VERSION == 1

- name: Push configuration to router.
  edgeos_config:
    src: ~/_ans_tmp/config.boot-{{ erlcfg.system.hostname }}.{{ erlcfg.system.domain_name }}
